name: Anchor SBOM internal Action

description: Anchor SBOM internal Action

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true
  
  slsa-workflow-secret1:
    description: 'secret1 stores the registry username'
    type: string
    required: false

  slsa-workflow-secret2:
    description: 'secret2 stores the github-token'
    type: string
    required: false
  
  # Unused secret inputs.
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

runs:
  using: 'composite'
  steps:
    # NOTE: the repository is already cloned by the caller, so there's no need to
    # checkout ourselves.

    - name: Download artifact
      if: ${{ startsWith(github.ref, 'refs/tags/') && fromJson(inputs.slsa-workflow-inputs).file != '' }}
      env:
        GH_TOKEN: ${{ github.token }}
        UNTRUSTED_TAG: ${{ github.ref }}
        UNTRUSTED_ASSET: ${{ fromJson(inputs.slsa-workflow-inputs).file }}
      shell: bash
      run: ./../__TOOL_ACTION_DIR__/download-file.sh
        

    # This calls the main Action, e.g., ./../__TOOL_CHECKOUT_DIR__/<path/to/action>
    # if path is left empty, the Action's action.yml is located at the root of the repository.
    - name: Run main sbom-action Action
      uses: ./../__TOOL_CHECKOUT_DIR__
      with:
        path: ${{ fromJson(inputs.slsa-workflow-inputs).path }}
        file: ${{ fromJson(inputs.slsa-workflow-inputs).file }}
        image: ${{ fromJson(inputs.slsa-workflow-inputs).image }}
        registry-username: ${{ fromJson(inputs.slsa-workflow-inputs).registry-username }}
        format: ${{ fromJson(inputs.slsa-workflow-inputs).format }}
        artifact-name: ${{ fromJson(inputs.slsa-workflow-inputs).artifact-name }}
        #output-file: ${{ fromJson(inputs.slsa-workflow-inputs).output-file }}
        syft-version: ${{ fromJson(inputs.slsa-workflow-inputs).syft-version }}
        dependency-snapshot: ${{ fromJson(inputs.slsa-workflow-inputs).dependency-snapshot }}
        upload-artifact: ${{ fromJson(inputs.slsa-workflow-inputs).upload-artifact }}
        upload-release-assets: ${{ fromJson(inputs.slsa-workflow-inputs).upload-release-assets }}
        registry-password: ${{ inputs.slsa-workflow-secret1 }}
        github-token: ${{ inputs.slsa-workflow-secret2 || github.token}}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        #UNTRUSTED_OUTPUT_FILE: ${{ fromJson(inputs.slsa-workflow-inputs).output-file }}
      shell: bash
      # The `slsa-build-action-path` is available at `./../__TOOL_ACTION_DIR__`.
      run: ./../__TOOL_ACTION_DIR__/generate-layout.sh