name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: [feature, enhancement]
  - title: "🐛 Bug Fixes"
    labels: [fix, bugfix, bug]

change-template: "- $TITLE (#$NUMBER)"

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch

template: |
  ## Changes in v$RESOLVED_VERSION

  $CHANGES
