rules:
  unpinned-uses:
    config:
      policies:
        # anchore/workflows is an internal repository; using @main is acceptable
        anchore/*: any

  secrets-outside-env:
    ignore:
      - update-syft-release.yml:35
      - update-syft-release.yml:36
