name: "Anchore SBOM Action / Attach SBOM to Release"
description: "Creates an SBOM (Software Bill Of Materials) from your code and container images"
author: "Anchore"
inputs:
  sbom-artifact-match:
    required: false
    description: "A regex to find SBOM artifacts to attach to a release"
    default: ".*\\.spdx\\.json$"

  github-token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "../dist/attachReleaseAssets/index.js"
