name: "Anchore SBOM Action / Download Syft"
description: "Downloads Syft to the Action tool cache and provides a reference"
author: "Anchore"

inputs:
  syft-version:
    required: false
    description: "The version of Syft to download"

outputs:
  cmd:
    description: "A reference to the Syft command"

runs:
  using: "node20"
  main: "../dist/downloadSyft/index.js"
