name: "Anchore SBOM Action / Download Syft"
description: "Downloads Syft to the Action tool cache and provides a reference"
author: "Anchore"

outputs:
  cmd:
    description: "A reference to the Syft command"

runs:
  using: "node12"
  main: "../dist/downloadSyft/index.js"
