name: Re-tag releases

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # v2.0.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          publish_latest_tag: true
