name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
