name: Anchor SLSA3 SBOM builder

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  workflow_call:

    secrets:
      registry-password:
        required: false
        description: "The registry password"

      github-token:
        description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
        required: false
        default: ${{ github.token }}

      path:
        required: false
        description: "A path to a directory on the filesystem to scan"
        default: "."

      file:
        required: false
        description: "A file on the filesystem to scan"

      image:
        required: false
        description: "A container image to scan"

      registry-username:
        required: false
        description: "The registry username"

      format:
        required: false
        description: "The SBOM format to export"
        default: "spdx-json"

      artifact-name:
        description: "The name to use for the SBOM file generated by this action"
        required: false

      output-file:
        required: false
        description: "A file location to output the SBOM"

      syft-version:
        required: false
        description: "The version of Syft to use"

      dependency-snapshot:
        required: false
        description: "Upload to GitHub dependency snapshot API"
        default: "false"

      upload-artifact:
        required: false
        description: "Upload artifact to workflow"
        default: "true"

      upload-release-assets:
        required: false
        description: "Upload release assets"
        default: "true"

      private-repository:
        description: "TODO"
        required: false
        type: boolean
        default: false

      # TODO    
      # provenance-overwrite:
      #   description: "overwrite provenance if already present"
      #   required: false
      #   type: boolean
      #   default: false

jobs:
  slsa-setup:
    permissions:
      id-token: write # For token creation.
    outputs:
      slsa-token: ${{ steps.generate.outputs.slsa-token }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate the token
        id: generate
        uses: laurentsimon/slsa-delegator/actions/setup-token@main
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-private-repository: true
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./internal/sbom-wrapper"
          # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/1575): mask sensitive fields.
          slsa-workflow-inputs: ${{ toJson(inputs) }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read   # For the entrypoint.
      packages: write
    uses: laurentsimon/slsa-delegator/.github/workflows/delegator_generic_slsa3.yml@main
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}
    secrets:
      secret1: ${{ secrets.registry-password }}
      secret2: ${{ secrets.github-token }}

  slsa-publish:
    needs: [slsa-run]
    permissions:
      contents: write # For asset uploads. Optional
    runs-on: ubuntu-latest
    steps:
      - name: Verify and publish
        env:
          SLSA_ATTESTATION_DOWNLOAD_NAME: ${{ needs.slsa-run.outputs.attestations-download-name }}
        run: |
          echo "download from $SLSA_ATTESTATION_DOWNLOAD_NAME"
          echo "artifacts $ACTION_ARTIFACTS"

          # Download artifacts and provenance
          # Verify thru slsa-verifier

          # Upload the attestation.

